version: "3.9"
services:
  backend:
    build: ./backend
    command: uvicorn app.main:app --host 0.0.0.0 --port 8000 --reload
    volumes:
      - ./backend/app:/app/app
      - ./backend/data:/app/data
    environment:
      - DATABASE_URL=postgresql+psycopg2://postgres:postgres@db:5432/traffic
    depends_on:
      - db
      - redis
    ports:
      - "8000:8000"
  db:
    image: postgres:15
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=traffic
    volumes:
      - db_data:/var/lib/postgresql/data
    ports:
      - "5433:5432"
  redis:
    image: redis:7
    ports:
      - "6379:6379"
  frontend:
    build: ./frontend
    command: ["sh", "-c", "npm install && npm run build && npx serve -s dist"]
    working_dir: /app
    volumes:
      - ./frontend:/app
    ports:
      - "3000:3000"
    depends_on:
      - backend
volumes:
  db_data: {}
